"""
ArtNode KGTG Provenance Service
Implements cryptographic anchoring for provenance records:
1. Generate PDF provenance report (WeasyPrint)
2. SHA-256 hash the PDF
3. Submit hash to OpenTimestamps (Bitcoin blockchain)
4. Optional GPG sign
5. Store all artifacts in MinIO

Legal note: OTS timestamps are cryptographically strong but not qualified
under Swiss ZertES or eIDAS. For legally binding timestamps, use a qualified
TSA (e.g. SwissSign). OTS is suitable for due diligence documentation.
"""
import hashlib
import io
import os
import tempfile
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def _minio_client():
    from minio import Minio
    return Minio(
        os.environ.get("MINIO_ENDPOINT", "garage:3900"),
        access_key=os.environ.get("MINIO_ROOT_USER", os.environ.get("MINIO_ROOT_USER")),
        secret_key=os.environ.get("MINIO_ROOT_PASSWORD", ""),
        secure=False,
    )


def _ensure_bucket(client):
    bucket = os.environ.get("MINIO_BUCKET", "artnode-media")
    if not client.bucket_exists(bucket):
        client.make_bucket(bucket)
    return bucket


def generate_provenance_pdf(provenance, artwork, gallery):
    """
    Generate a PDF provenance report for a single event using WeasyPrint.
    Returns bytes.
    """
    from weasyprint import HTML

    artist = artwork.contact_artist
    artist_name = f"{artist.first_name or ''} {artist.last_name or ''}".strip() if artist else "Unknown"

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <style>
      body {{ font-family: 'Helvetica Neue', Helvetica, sans-serif; font-size: 11pt; color: #111; margin: 40px; }}
      h1 {{ font-size: 16pt; font-weight: 300; letter-spacing: 0.1em; text-transform: uppercase; border-bottom: 1px solid #ccc; padding-bottom: 8px; }}
      .meta {{ display: grid; grid-template-columns: 160px 1fr; gap: 6px 16px; margin: 24px 0; }}
      .label {{ color: #666; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.08em; }}
      .value {{ font-size: 10pt; }}
      .footer {{ margin-top: 48px; font-size: 8pt; color: #999; border-top: 1px solid #eee; padding-top: 8px; }}
      .warning {{ font-size: 8pt; color: #c0392b; margin-top: 8px; }}
    </style>
    </head>
    <body>
    <h1>Provenance Record</h1>
    <div class="meta">
      <span class="label">Gallery</span>
      <span class="value">{gallery.public_name or gallery.name}</span>

      <span class="label">Artwork</span>
      <span class="value">{artwork.title}</span>

      <span class="label">Artist</span>
      <span class="value">{artist_name}</span>

      <span class="label">Inventory No.</span>
      <span class="value">{artwork.inventory_number or '—'}</span>

      <span class="label">Event Type</span>
      <span class="value">{provenance.event_type}</span>

      <span class="label">Event Date</span>
      <span class="value">{provenance.event_date.strftime('%d %B %Y') if provenance.event_date else '—'}</span>

      <span class="label">Source / Party</span>
      <span class="value">{provenance.source_name or '—'}</span>

      <span class="label">Country</span>
      <span class="value">{provenance.source_country or '—'}</span>

      <span class="label">Description</span>
      <span class="value">{provenance.description or '—'}</span>

      <span class="label">Recorded By</span>
      <span class="value">{provenance.recorded_by.email if provenance.recorded_by else '—'}</span>

      <span class="label">Recorded At</span>
      <span class="value">{provenance.recorded_at.strftime('%d %B %Y %H:%M UTC') if provenance.recorded_at else '—'}</span>

      <span class="label">Record ID</span>
      <span class="value">artnode.provenance.{provenance.id}</span>
    </div>

    <div class="footer">
      Generated by ArtNode — {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}
      <div class="warning">
        Note: OpenTimestamps (OTS) blockchain anchoring provides cryptographic proof of existence
        but is not a qualified electronic timestamp under Swiss ZertES or EU eIDAS regulation.
        For legally binding timestamps, use a qualified TSA (e.g. SwissSign).
      </div>
    </div>
    </body>
    </html>
    """
    return HTML(string=html).write_pdf()


def sha256_bytes(data: bytes) -> str:
    """Return hex SHA-256 of data."""
    return hashlib.sha256(data).hexdigest()


def submit_ots(pdf_bytes: bytes) -> bytes:
    """
    Submit SHA-256 of PDF to OpenTimestamps and return the .ots proof bytes.
    This is async — the proof will be incomplete until Bitcoin confirms (~1hr).
    """
    try:
        import subprocess
        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as f:
            f.write(pdf_bytes)
            pdf_path = f.name

        ots_path = pdf_path + '.ots'
        result = subprocess.run(
            ['ots', 'stamp', pdf_path],
            capture_output=True, text=True, timeout=120
        )
        logger.info(f"OTS stamp stdout: {result.stdout}")
        logger.info(f"OTS stamp stderr: {result.stderr}")

        if os.path.exists(ots_path):
            with open(ots_path, 'rb') as f:
                ots_bytes = f.read()
            os.unlink(pdf_path)
            os.unlink(ots_path)
            return ots_bytes
        else:
            logger.warning("OTS stamp did not produce .ots file")
            os.unlink(pdf_path)
            return None
    except Exception as e:
        logger.error(f"OTS submission failed: {e}")
        return None


def gpg_sign(pdf_bytes: bytes, gpg_key_id: str = None) -> bytes:
    """
    GPG-sign the PDF bytes. Returns detached .sig bytes or None if no key.
    """
    if not gpg_key_id:
        logger.info("No GPG key configured — skipping signature")
        return None
    try:
        import gnupg
        gpg = gnupg.GPG()
        signed = gpg.sign(pdf_bytes, keyid=gpg_key_id, detach=True, binary=True)
        if signed:
            return signed.data
        logger.warning("GPG signing returned empty result")
        return None
    except Exception as e:
        logger.error(f"GPG signing failed: {e}")
        return None


def store_in_minio(bucket, client, object_name, data_bytes, content_type):
    """Store bytes in MinIO, return object path."""
    client.put_object(
        bucket, object_name,
        io.BytesIO(data_bytes), len(data_bytes),
        content_type=content_type
    )
    return object_name


def anchor_provenance(provenance, artwork, gallery, gpg_key_id=None):
    """
    Full KGTG anchoring pipeline for a provenance record.
    1. Generate PDF
    2. SHA-256 hash
    3. Submit to OTS
    4. Optional GPG sign
    5. Store in MinIO
    6. Update provenance record fields
    Returns dict with status info.
    """
    from .extensions import db

    result = {"status": "ok", "steps": []}

    try:
        # Step 1: Generate PDF
        pdf_bytes = generate_provenance_pdf(provenance, artwork, gallery)
        result["steps"].append("pdf_generated")

        # Step 2: Hash
        doc_hash = sha256_bytes(pdf_bytes)
        result["hash"] = doc_hash
        result["steps"].append("hash_computed")

        # Step 3: MinIO client
        client = _minio_client()
        bucket = _ensure_bucket(client)
        base = f"provenance/{gallery.id}/{artwork.id}/{provenance.id}"

        # Step 4: Store PDF
        pdf_path = store_in_minio(
            bucket, client,
            f"{base}/provenance_{provenance.id}.pdf",
            pdf_bytes, "application/pdf"
        )
        result["steps"].append("pdf_stored")

        # Step 5: OTS timestamp
        ots_bytes = submit_ots(pdf_bytes)
        ots_path = None
        if ots_bytes:
            ots_path = store_in_minio(
                bucket, client,
                f"{base}/provenance_{provenance.id}.pdf.ots",
                ots_bytes, "application/octet-stream"
            )
            result["steps"].append("ots_submitted")
        else:
            result["steps"].append("ots_skipped")

        # Step 6: GPG sign (optional)
        sig_path = None
        if gpg_key_id:
            sig_bytes = gpg_sign(pdf_bytes, gpg_key_id)
            if sig_bytes:
                sig_path = store_in_minio(
                    bucket, client,
                    f"{base}/provenance_{provenance.id}.pdf.sig",
                    sig_bytes, "application/pgp-signature"
                )
                result["steps"].append("gpg_signed")

        # Step 7: Update DB record
        provenance.document_hash = doc_hash
        provenance.document_path = pdf_path
        provenance.ots_file_path = ots_path
        provenance.gpg_sig_path = sig_path
        provenance.ots_status = "submitted" if ots_bytes else "pending"
        db.session.commit()
        result["steps"].append("db_updated")

    except Exception as e:
        logger.error(f"KGTG anchoring failed for provenance {provenance.id}: {e}")
        result["status"] = "error"
        result["error"] = str(e)

    return result
