"""phase 3b contact artist unification

Revision ID: 0d0055c47058
Revises: f5ef8b7cb0b6
Create Date: 2026-05-26 16:20:59.226989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0055c47058'
down_revision = 'f5ef8b7cb0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contact', ['contact_artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contact_artist_id')

    # ### end Alembic commands ###
