"""add artist fields to contact

Revision ID: 1651d32899d5
Revises: 0d0055c47058
Create Date: 2026-05-26 16:23:56.730858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1651d32899d5'
down_revision = '0d0055c47058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('biography', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('death_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sort_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cv_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('artist_website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active_representation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('legacy_artist_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('legacy_artist_id')
        batch_op.drop_column('is_active_representation')
        batch_op.drop_column('artist_website')
        batch_op.drop_column('cv_json')
        batch_op.drop_column('slug')
        batch_op.drop_column('sort_name')
        batch_op.drop_column('nationality')
        batch_op.drop_column('death_year')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('biography')
        batch_op.drop_column('roles')
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
