"""add font_pairing to gallery

Revision ID: 1d96a2b03947
Revises: f3812cd81b19
Create Date: 2026-06-13 18:44:34.653203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d96a2b03947'
down_revision = 'f3812cd81b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_pairing', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('font_pairing')

    # ### end Alembic commands ###
