"""KGTG provenance fields

Revision ID: 1e514d2db7cf
Revises: c82a4bf0e36c
Create Date: 2026-05-27 16:36:02.395138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e514d2db7cf'
down_revision = 'c82a4bf0e36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('document_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ots_file_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gpg_sig_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ots_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.drop_column('ots_status')
        batch_op.drop_column('gpg_sig_path')
        batch_op.drop_column('ots_file_path')
        batch_op.drop_column('document_path')
        batch_op.drop_column('document_hash')

    # ### end Alembic commands ###
