"""add gallery public fields and viewing room tables

Revision ID: 38f6f7263a4d
Revises: 
Create Date: 2026-05-18 16:01:09.390689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f6f7263a4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewing_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('access_code_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewing_room_artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viewing_room_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.id'], ),
    sa.ForeignKeyConstraint(['viewing_room_id'], ['viewing_room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viewing_room_id', 'artwork_id', name='uq_viewing_room_artwork')
    )
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tagline', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('about_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('website_custom_domain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('website_custom_domain')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('about_text')
        batch_op.drop_column('tagline')
        batch_op.drop_column('public_name')

    op.drop_table('viewing_room_artwork')
    op.drop_table('viewing_room')
    # ### end Alembic commands ###
