"""add Art 24a acquisition fields to artwork_provenance

Revision ID: 39f5c97c75ea
Revises: a1b2c3d4e5f6
Create Date: 2026-06-10 15:47:39.708498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f5c97c75ea'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_consignment', schema=None) as batch_op:
        batch_op.alter_column('is_secondary_market',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('supplier_vat_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('right_of_disposal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('retention_30yr', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.drop_column('retention_30yr')
        batch_op.drop_column('right_of_disposal')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('supplier_vat_status')
        batch_op.drop_column('supplier_address')

    with op.batch_alter_table('artwork_consignment', schema=None) as batch_op:
        batch_op.alter_column('is_secondary_market',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
