"""add translations JSONB to contact artwork exhibition

Revision ID: 48b213ec1748
Revises: da36ec082756
Create Date: 2026-06-06 09:22:00.357796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b213ec1748'
down_revision = 'da36ec082756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True))

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True))

    with op.batch_alter_table('exhibition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibition', schema=None) as batch_op:
        batch_op.drop_column('translations')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('translations')

    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.drop_column('translations')

    # ### end Alembic commands ###
