"""add is_public to artwork

Revision ID: 6f002988cd3f
Revises: d306a1285c19
Create Date: 2026-05-26 17:16:31.905691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f002988cd3f'
down_revision = 'd306a1285c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
