"""add invoice payment and acquisition fields

Revision ID: 75dab538938f
Revises: 38f6f7263a4d
Create Date: 2026-05-19 16:44:03.011703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dab538938f'
down_revision = '38f6f7263a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ownership_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('acquisition_cost', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('acquisition_date')
        batch_op.drop_column('acquisition_cost')
        batch_op.drop_column('ownership_type')

    # ### end Alembic commands ###
