"""add maintenance_mode to gallery

Revision ID: 768828fb6647
Revises: c91e23e69dc1
Create Date: 2026-06-11 17:15:33.308607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768828fb6647'
down_revision = 'c91e23e69dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('maintenance_mode')

    # ### end Alembic commands ###
