"""move translations to artwork, remove from provenance

Revision ID: 9acb4121ba6b
Revises: 48b213ec1748
Create Date: 2026-06-06 09:23:25.842386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9acb4121ba6b'
down_revision = '48b213ec1748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True))

    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.drop_column('translations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('translations')

    # ### end Alembic commands ###
