"""add language and translation_group_id to blog_post

Revision ID: b05f741563a1
Revises: 9acb4121ba6b
Create Date: 2026-06-06 10:11:09.989382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05f741563a1'
down_revision = '9acb4121ba6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('translation_group_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('translation_group_id')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
