"""add purchase_invoice_number to artwork_provenance

Revision ID: b4d2614f9ff6
Revises: 39f5c97c75ea
Create Date: 2026-06-10 16:02:57.793348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d2614f9ff6'
down_revision = '39f5c97c75ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_invoice_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.drop_column('purchase_invoice_number')

    # ### end Alembic commands ###
