"""provenance attached files

Revision ID: b8a9d8598a79
Revises: 1e514d2db7cf
Create Date: 2026-05-27 17:06:48.652432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8a9d8598a79'
down_revision = '1e514d2db7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attached_files', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_provenance', schema=None) as batch_op:
        batch_op.drop_column('attached_files')

    # ### end Alembic commands ###
