"""add logo_url to gallery

Revision ID: c82a4bf0e36c
Revises: 6f002988cd3f
Create Date: 2026-05-26 17:52:55.711088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82a4bf0e36c'
down_revision = '6f002988cd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('sort_name', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('cv_json', sa.JSON(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active_representation', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'artist', ['artist_id'], ['id'])

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')

    op.drop_table('artist')
    # ### end Alembic commands ###
