"""add is_active_show to exhibition

Revision ID: d306a1285c19
Revises: 1651d32899d5
Create Date: 2026-05-26 17:01:41.560814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd306a1285c19'
down_revision = '1651d32899d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active_show', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibition', schema=None) as batch_op:
        batch_op.drop_column('is_active_show')

    # ### end Alembic commands ###
