"""add artist fields and artwork flags

Revision ID: f5ef8b7cb0b6
Revises: 75dab538938f
Create Date: 2026-05-20 14:37:24.293513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ef8b7cb0b6'
down_revision = '75dab538938f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_carousel', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('is_carousel')
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
